---
title: "Analysis - global section"
author: "Jens Daniel Müller and Donghe Zhu"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r read_params_local, include = FALSE}
params_local <-
  read_rds(here::here("data/auxillary",
                       "params_local.rds"))

```

```{r define_paths, include = FALSE}

path_model <-
  paste(path_root, "/model/", sep = "")

path_preprocessing    <-
  paste(path_model, "preprocessing/", sep = "")

path_version_data     <-
  paste(path_model,
        params_local$Version_ID,
        "/data/",
        sep = "")

path_version_figures  <-
  paste(path_model,
        params_local$Version_ID,
        "/figures/",
        sep = "")
```


```{r load_libraries_specific, include = FALSE}
library(scales)
library(marelac)
library(gt)
```

# Data sources

Following Cant estimates are used:

- Mean and SD per grid cell for this study and model truth (basin, lat, lon, eras)


## This study

Results from this study are referred to as JDM.

```{r read_JDM_cant_file}

cant_3d <-
  read_csv(paste(path_version_data,
                 "cant_3d.csv",
                 sep = ""))

```

## Modeled Cant

"True" Cant fields directly inferred from the model output are referred to as M.

```{r read_model_cant_files}
               
tref  <-
  read_csv(paste(path_version_data,
                 "tref.csv",
                 sep = ""))

cant_tref_1 <-
  read_csv(paste(
    path_preprocessing,
    "cant_annual_field_", params_local$model_runs, "/cant_",
    unique(tref$year[1]),
    ".csv",
    sep = ""
  ))

cant_tref_1 <- cant_tref_1 %>%
  rename(cant_tref_1 = cant_total) %>%
  select(-year)

cant_tref_2 <-
  read_csv(paste(
    path_preprocessing,
    "cant_annual_field_", params_local$model_runs, "/cant_",
    unique(tref$year[2]),
    ".csv",
    sep = ""
  ))

cant_tref_2 <- cant_tref_2 %>%
  rename(cant_tref_2 = cant_total) %>%
  select(-year)

cant_tref_3 <-
  read_csv(paste(
    path_preprocessing,
    "cant_annual_field_", params_local$model_runs, "/cant_",
    unique(tref$year[3]),
    ".csv",
    sep = ""
  ))

cant_tref_3 <- cant_tref_3 %>%
  rename(cant_tref_3 = cant_total) %>%
  select(-year)

```

```{r calc_model_cant_between_tref}

cant_M_1 <- left_join(cant_tref_1, cant_tref_2) %>%
  mutate(cant = cant_tref_2 - cant_tref_1,
         eras = unique(cant_3d$eras)[1]) %>%
  select(-c(cant_tref_1, cant_tref_2))

cant_M_1 <- cant_M_1 %>%
  mutate(cant_pos = if_else(cant <= 0, 0, cant))

cant_M_2 <- left_join(cant_tref_2, cant_tref_3) %>%
  mutate(cant = cant_tref_3 - cant_tref_2,
         eras = unique(cant_3d$eras)[2]) %>%
  select(-c(cant_tref_2, cant_tref_3))

cant_M_2 <- cant_M_2 %>%
  mutate(cant_pos = if_else(cant <= 0, 0, cant))

cant_M <- full_join(cant_M_1, cant_M_2) %>%
  arrange(lon, lat, depth, basin_AIP)

rm(cant_tref_1, cant_tref_2, cant_tref_3, cant_M_1, cant_M_2)

```


# Global mean sections

## Cant - positive only

```{r cant_global_sections_positive_mean, fig.asp=0.6}

for (i_eras in unique(cant_3d$eras)) {
  
  print(p_section_global(
    df = cant_3d %>% filter(eras == i_eras),
    var = "cant_pos",
    subtitle_text = paste("Eras:", i_eras, "| Estimate: JDM")
  ))
  
}

for (i_eras in unique(cant_M$eras)) {
  
  print(p_section_global(
    df = cant_M %>% filter(eras == i_eras),
    var = "cant_pos",
    subtitle_text = paste("Eras:", i_eras, "| Estimate: M")
  ))
  
}

```

## Cant - all

```{r cant_global_sections_all_mean, fig.asp=0.6}

for (i_eras in unique(cant_3d$eras)) {
  
  print(p_section_global(
    df = cant_3d %>% filter(eras == i_eras),
    var = "cant",
    subtitle_text = paste("Eras:", i_eras, "| Estimate: JDM")
  ))
  
}

for (i_eras in unique(cant_M$eras)) {
  
  print(p_section_global(
    df = cant_M %>% filter(eras == i_eras),
    var = "cant",
    subtitle_text = paste("Eras:", i_eras, "| Estimate: M")
  ))
  
}

```
