---
title: "Parameterization"
author: "Jens Daniel Müller and Donghe Zhu"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library, include=FALSE}
library(tidyverse)
```


# Definition

The following local parametrisations (i.e. relevant for this sensitivity run) were defined to run the analysis:

```{r define_params_local, class.source = 'fold-show'}

############### Some mannual work before running the full reconstruction
# change "config_parameterization_local": 
#    Stoichiometricratio C:P and N:P based on predictor phosphate or nitrate
#    model_resolution month or annual
#    nan_fill yes or no
#    flag_f add 9
#    basin separation
#    slab number
#    depth and neutral density threshold
# change "eMLR_GLODAPv2_2020_subsetting": ()/_ann
# change "eMLR_model_fitting": remove multicolinearity combination


# neutral density thresholds to cut the Atlantic ocean into slabs
slabs_Atl <-
  c(
    -Inf,
    26.00,
    26.50,
    26.75,
    27.00,
    27.25,
    27.50,
    27.75,
    27.85,
    #27.91,##
    27.95,
    #27.97,##
    #28.00,##
    28.05,
    28.10,
    28.15,
    28.20,
    Inf
  )

# neutral density thresholds to cut the Indo-Pacific ocean into slabs [increase 28.20, 28.30]
slabs_Ind_Pac <-
  c(-Inf,
    26.00,
    26.50,
    26.75,
    27.00,
    27.25,
    27.50,
    27.75,
    27.85,
    27.95,
    28.05,
    28.10,
    28.20,
    28.30,
    Inf)

# Predictors for MLR model
MLR_predictors <- c(
            #    "sal",
                "temp",
                "oxygen",
                "aou",
                "nitrate",
            #    "silicate",
            #    "silicate_star",
                "phosphate",
                "phosphate_star"
            )

params_local <-
  lst(
    # resolution: annual / month
    model_resolution = "month",
    # the GOBM used for subsetting, currently with options of CESM ("") or NorESM ("NorESM/") or FESOM_REcoM_LR ("FESOM_REcoM_LR/") or ORCA025 ("ORCA025/")
    GOBM = "ORCA025/",
    # Whether use NaN filled GLODAP subset (yes or no)
    nan_fill = "no",
    # model climate forcing with options of variable ("AD") or constant ("CB")
    model_runs = "AD",
    # model subsetting with options of "GLODAP" or "random"
    subsetting = "GLODAP",
    # random subsetting with options of "grid" or "lat"
    random = "lat",
    # ID of current sensitivity run
    Version_ID = "v_XXX",
    # f flags accepted for GLODAP data
    flag_f = c(2, 0),
    # qc flags accepted for GLODAP data
    flag_qc = c(1, 0),
    # Should A16 cruise from 2013/14 be included in middle era (y/n)
    A16_GO_SHIP = "n",
    # Shallowest depth for data to be included in MLR fitting (standard: 150; no sfc: 0)
    depth_min = 150,
    # Shallowest water depth for data to be included in MLR fitting
    bottomdepth_min = 0,
    # Lowest neutral density to map Cant with eMLR approach (in surface layer?) (standard:26, all latitude sfc approach: set as 30)
    gamma_min = 26,
    # break years for eras, numbers indicate the upper end of the respective era
    era_breaks_GLODAP_start = c(1982, 2000, 2010),
    era_breaks_GLODAP_end = c(1999, 2009, 2019),
    era_breaks_random_start = c(1982, 2000, 2010),
    era_breaks_random_end = c(1999, 2009, 2019),
    # era_breaks_GLODAP = c(1981, 1999, 2009, Inf),
    # era_breaks_random = c(1981, 1999, 2009, Inf),
    # whether use median year as the tref
    median_tref = "y",
    # ID for basins for MLR fits: 2, 5, SO, AIP, SO_5
    MLR_basins = "2",
    # Select the target variable for MLR, either "tco2", "cstar" or "cstar_tref"
    MLR_target = "cstar_tref",
    # see above
    MLR_predictors = MLR_predictors,
    # Maximum number of MLR predictors
    MLR_predictors_max = 5,
    # Minimum number of MLR predictors
    MLR_predictors_min = 2,
    # Total number of MLR fits taken into account
    MLR_number = 10,
    # Fitted model type rlm or lm
    MLR_type = "lm",
    # Criterion to select best MLR fits, either "rmse" or "aic" or "rank"
    MLR_criterion = "rmse",
    # VIF threshold (set vif = 1000 to apply slightly vif filter)
    vif_max = 1000,
    # see above
    slabs_Atl = slabs_Atl,
    # see above
    slabs_Ind_Pac = slabs_Ind_Pac,
    # Stoichiometric ratio of C to P (Phosphate-based: 117; Nitrate-based: 117/16)
    rCP = 117,
    # Stoichiometric ratio of N to P (Phosphate-based: 16; Nitrate-based: 1)
    rNP = 16,
    # Stoichiometric ratio of P to O (PO4* calculation)
    rPO = 170,
    # Offset P to O (PO4* calculation)
    rPO_offset = 1.95,
    # surface DIC calculation with options of "revelle factor" or "atmospheric equilibrium" or "atmospheric pCO2 increase"
    surface_DIC_calculation = "revelle factor",
    # Preindustrial atmospheric pCO2
    preind_atm_pCO2 = 280,
    # generate a high number of diagnostic plots while running the analysis (y/n)
    plot_all_figures = "n"
  )

```

# Write file

Parameterization criteria are locally stored and used throughout this sensitivty case.

```{r write_params_local}

params_local %>%
  write_rds(here::here("data/auxillary",
                       "params_local.rds"))


```

# Create folders

Folders for each new sensitivity run are automatically created.

```{r create_folder_structure, include=FALSE}

path_root           <- "/nfs/kryo/work/jenmueller/emlr_cant/model"

dir.create(paste(path_root, params_local$Version_ID, sep = "/"))

dir.create(paste(path_root, params_local$Version_ID, "data", sep = "/"))

dir.create(paste(path_root, params_local$Version_ID, "figures", sep = "/"))
dir.create(paste(path_root, params_local$Version_ID, "figures/Cant_model_sections", sep = "/"))
dir.create(paste(path_root, params_local$Version_ID, "figures/Cruise_sections_histograms", sep = "/"))
dir.create(paste(path_root, params_local$Version_ID, "figures/eMLR_diagnostics", sep = "/"))
dir.create(paste(path_root, params_local$Version_ID, "figures/Observations_correlation", sep = "/"))

```
